name: Build and distribute

on:
    workflow_dispatch:
        inputs:
            branch_name:
                description: "Branch to run the workflow on"
                required: true
                default: "main"

jobs:
    build_android:
        name: build_android
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4

          - uses: cedvdb/action-flutter-build-android@v1
            with:
                keystore-base64: ${{ secrets.ANDROID_RELEASE_KEY }}
                keystore-password: "${{ secrets.ANDROID_RELEASE_KEY_PASSWORD }}"
                # optionals
                build-cmd: flutter build apk --release --flavor dev
                working-directory: ./habit_task_tracker/

          - name: Archive APK
            uses: actions/upload-artifact@v4
            with:
                name: release-apk
                # Try running the build locally with the build command to be sure of this path
                path: habit_task_tracker/build/app/outputs/flutter-apk/app-dev-release.apk

    build_ios:
        name: build_ios
        runs-on: macos-latest
        steps:
          - uses: actions/checkout@v4

          - uses: cedvdb/action-flutter-build-ios@v1
            with:
                # always use --export-options-plist=ios/GithubActionsExportOptions.plist
                build-cmd: flutter build ipa --release --flavor dev --export-options-plist=ios/GithubActionsExportOptions.plist
                certificate-base64: ${{ secrets.IOS_BUILD_CERTIFICATE_BASE64 }}
                certificate-password: ${{ secrets.IOS_BUILD_CERTIFICATE_PASSWORD }}
                provisioning-profile-base64: ${{ secrets.IOS_MOBILE_PROVISIONING_PROFILE_BASE64 }}
                keychain-password: ${{ secrets.IOS_GITHUB_KEYCHAIN_PASSWORD }}
                working-directory: ./habit_task_tracker/

          - name: Archive IPA
            uses: actions/upload-artifact@v4
            with:
                name: release-ipa
                # Try running the build locally with the build command to be sure of this path
                path: habit_task_tracker/build/ios/ipa/App-dev.ipa
